name: uboot-build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The branch to build'
        required: true
        default: 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt update
          sudo -E apt -y install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: make
        run: |
          ls uboot-mtk-20230718-09eda825/configs/mt7981_* |grep -v rfb | xargs -i basename {} |awk -F 'mt7981_' '{print $2}'|awk -F '_defconfig' '{print $1}'|awk -F '_multi_layout' '{print $1}'|uniq -c|awk '{ if($1==2)  {print "SOC=mt7981 BOARD="$2,"MULTI_LAYOUT=1 ./build.sh"} else {print "SOC=mt7981 BOARD="$2,"./build.sh"}}'| bash
          ls uboot-mtk-20230718-09eda825/configs/mt7986_* |grep -v rfb | xargs -i basename {} |awk -F 'mt7986_' '{print $2}'|awk -F '_defconfig' '{print $1}'|awk -F '_multi_layout' '{print $1}'|uniq -c|awk '{ if($1==2)  {print "SOC=mt7986 BOARD="$2,"MULTI_LAYOUT=1 ./build.sh"} else {print "SOC=mt7986 BOARD="$2,"./build.sh"}}'| bash
  
      - name: check
        run: |
          ls -lh output
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
  

      - name: Upload uboot
        uses: actions/upload-artifact@v3
        with:
          name: bl-mt798x-release-${{ env.CURRENT_DATE }}
          path: ./output/


      - name: Upload firmware to release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.CURRENT_DATE }}
          files: ./output/*
